# Spring Boot 설정
spring:
  # JPA (Java Persistence API) 설정
  jpa:
    # Hibernate가 DB 스키마를 다루는 방식 설정
    hibernate:
      # ddl-auto: 엔티티 클래스를 기준으로 데이터베이스 스키마를 자동으로 생성, 수정, 삭제
      #   - create: 기존 테이블 삭제 후 새로 생성 (테스트용)
      #   - update: 기존 스키마를 유지하며 변경된 부분만 반영 (개발용)
      #   - validate: 엔티티와 테이블이 일치하는지 검증
      #   - none: 아무것도 하지 않음 (운영 환경 권장)
      ddl-auto: update
    # 실행되는 SQL 쿼리를 로그에 표시할지 여부
    show-sql: true
    # SQL 로그를 예쁘게 포맷팅
    properties:
      hibernate:
        format_sql: true

# 로깅 레벨 설정
logging:
  level:
    # Hibernate가 어떤 타입의 데이터를 바인딩하는지 로그에 표시
    org.hibernate.type.descriptor.sql: trace
