apiVersion: v1
kind: ConfigMap
metadata:
  name: task-api-config
data:
  # application.yml 파일의 내용을 이곳에서 중앙 관리합니다.
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://postgres-service:5432/taskdb
      redis:
        host: redis-service
        port: 6379
        connect-timeout: 5s
        lettuce:
          pool:
            max-active: 8
            max-wait: 1s
      jpa:
        hibernate:
          ddl-auto: update
    server:
      port: 8080

