apiVersion: apps/v1
kind: Deployment
metadata:
  # Deployment와 Service의 이름이 겹치지 않도록 명확하게 변경합니다.
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        # --- CPU / 메모리 리소스 설정 ---
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        # ★★★ readinessProbe를 추가하여 헬스 체크를 정의합니다. ★★★
        # 이 파드가 외부 요청을 받을 준비가 되었는지 확인합니다.
        readinessProbe:
          # 6379 포트에 TCP 연결을 시도하여 성공하면 준비된 것으로 간주합니다.
          tcpSocket:
            port: 6379
          # 컨테이너가 시작되고 5초 후에 첫 검사를 시작합니다.
          initialDelaySeconds: 5
          # 10초마다 검사를 반복합니다.
          periodSeconds: 10
---
# --- Redis Service ---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379